// Generated by tomekit to type `tomekit/content`. Commit it; it only changes if your config file moves.
import type config from "./tomekit.config";

declare module "tomekit" {
  interface Register {
    config: typeof config;
  }
}
