import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import { IBM_Plex_Mono as FontMono, Inter as FontSans } from "next/font/google";
import Link from "next/link";
import { Navbar } from "@/components/navbar";

const fontSans = FontSans({
  weight: ["400", "500", "600"],
  display: "swap",
  subsets: ["latin"],
  variable: "--sans",
});

const fontMono = FontMono({
  weight: ["400", "500", "600"],
  display: "swap",
  subsets: ["latin"],
  variable: "--mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background text-foreground font-sans leading-relaxed antialiased",
          fontSans.variable,
          fontMono.variable,
        )}
      >
        <Navbar />
        <main className="max-w-2xl mx-auto px-4 pb-20 space-y-20">
          {children}
        </main>
      </body>
    </html>
  );
}
